create table if not exists public.blacklist_domains (
  id bigint generated by default as identity primary key,
  domain text not null unique check (domain = lower(domain) and domain ~ '^[a-z0-9.-]+$'),
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected')),
  source text,
  notes text,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create index if not exists blacklist_domains_verified_idx
  on public.blacklist_domains (domain) where status = 'verified';

alter table public.blacklist_domains enable row level security;

-- Tabel sengaja tertutup untuk client. Endpoint Edge Function membaca dengan
-- service role; dashboard/admin pipeline yang menangani moderasi.
revoke all on public.blacklist_domains from anon, authenticated;

create or replace function public.set_verified_at()
returns trigger language plpgsql as $$
begin
  if new.status = 'verified' and old.status is distinct from 'verified' then
    new.verified_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists blacklist_set_verified_at on public.blacklist_domains;
create trigger blacklist_set_verified_at before update on public.blacklist_domains
for each row execute function public.set_verified_at();
